# Generated by Django 4.1.4 on 2023-01-11 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portcoreapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
    ]
