# Generated by Django 4.1.4 on 2023-01-31 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portcoreapi', '0002_rename_category_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name_of_category',
            field=models.CharField(max_length=64),
        ),
    ]
